name: build
on: [push]

jobs:
  build:
    name: build
    runs-on: macos-10.15
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install dependencies
        run: brew install flex bison
      - name: build
        env:
          MAC_SYSROOT: MacOSX10.15.sdk
          LIBO_FLEX_PATH: "/usr/local/opt/flex"
          CFLAGS: "-I/usr/local/opt/flex/include -I/usr/local/opt/bison/include -L/usr/local/opt/flex/lib -L/usr/local/opt/bison/lib"
          PATH: "/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:$PATH"
        run: |
          make
      - name: test
        env:
          MAC_SYSROOT: MacOSX10.15.sdk
          LIBO_FLEX_PATH: "/usr/local/opt/flex"
          CFLAGS: "-I/usr/local/opt/flex/include -I/usr/local/opt/bison/include -L/usr/local/opt/flex/lib -L/usr/local/opt/bison/lib"
          PATH: "/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:$PATH"
        run: make test
